import Link from "next/link";
import { ArrowRight, Database, Fingerprint, KeyRound, LockKeyhole, ShieldCheck, Trash2 } from "lucide-react";
import { Logo } from "@/components/logo";

const controls = [
  { icon: Database, title: "Customer-owned data plane", text: "Application rows remain in databases in your Supabase, Neon, and Cloudflare accounts. MeldDB stores control-plane metadata, not copies of query results." },
  { icon: LockKeyhole, title: "Encrypted provider credentials", text: "OAuth tokens, API keys, database passwords, and connection URIs are encrypted with AES-256-GCM and a versioned environment-held key." },
  { icon: KeyRound, title: "One-way API-key verification", text: "MeldDB project keys are random high-entropy secrets. Only a prefix and keyed SHA-256 verifier are retained; the raw key is shown once." },
  { icon: Fingerprint, title: "Tenant authorization", text: "Every project operation resolves the authenticated identity, membership, role, project, and resource. Provider resources cannot be addressed across projects." },
  { icon: Trash2, title: "Deliberate destruction", text: "Destructive SQL, key revocation, resource deletion, and project deletion use explicit confirmations. Project deletion preserves cloud resources by default." },
  { icon: ShieldCheck, title: "Bounded observability", text: "Logs exclude secrets and result payloads. Query metadata expires, usage is aggregated into time buckets, and errors carry request IDs." },
];

export default function SecurityPage() {
  return <main className="public-shell"><header className="public-nav"><Logo /><nav><Link href="/">Product</Link><Link href="/docs">Docs</Link><Link className="active" href="/security">Security</Link></nav><Link className="button secondary compact" href="/signup">Start building</Link></header><article className="security-content"><div className="security-hero"><span><ShieldCheck /></span><div className="eyebrow">Security and trust</div><h1>Your infrastructure<br />stays yours.</h1><p>MeldDB is designed for the uncomfortable reality that a control plane may hold credentials capable of accessing customer infrastructure. The system assumes bugs, leaked logs, stolen keys, and database exposure are possible—and limits the blast radius.</p></div><section className="security-grid">{controls.map(({ icon: Icon, title, text }) => <div key={title}><Icon /><h2>{title}</h2><p>{text}</p></div>)}</section><section className="security-detail"><div><small>PROVIDER ACCESS</small><h2>Scoped permissions, transparently used.</h2><p>OAuth integrations request management capabilities configured by the application owner. Neon uses a user-supplied API key because the V1 provider flow does not pretend an OAuth experience exists. Missing permissions become actionable states; they are not hidden behind a generic error.</p></div><div><small>OWNERSHIP</small><h2>Disconnect is not delete.</h2><p>Removing MeldDB access leaves customer provider resources intact. Deleting underlying infrastructure is a separate operation and never the default. If MeldDB disappeared, customer databases would remain in their provider accounts.</p></div></section><section className="security-boundary"><h2>Honest boundaries</h2><p>MeldDB does not claim SOC 2, ISO 27001, “bank-grade” security, arbitrary distributed SQL, or perfect isolation. Operational security still depends on strong deployment secrets, correctly scoped OAuth applications, dependency maintenance, database backups, provider policies, and prompt incident response.</p><Link href="/docs">Read the architecture and setup documentation <ArrowRight /></Link></section></article></main>;
}
