"use client";

import dynamic from "next/dynamic";
import { AlertTriangle, CloudUpload, FileCode2, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";

const MonacoEditor = dynamic(() => import("@monaco-editor/react"), { ssr: false, loading: () => <div className="editor-loading"><span /> Loading function editor…</div> });
interface FunctionItem { id?: string; slug?: string; status?: string; version?: string; verifyJwt?: boolean }
const initialSource = `Deno.serve(() => new Response(\n  JSON.stringify({ ok: true }),\n  { headers: { "content-type": "application/json" } },\n));\n`;

export function FunctionsManager({ projectId, resourceName }: { projectId: string; resourceName: string }) {
  const [items, setItems] = useState<FunctionItem[]>([]); const [selected, setSelected] = useState<string | null>(null); const [source, setSource] = useState(initialSource); const [slug, setSlug] = useState("hello-melddb"); const [verifyJwt, setVerifyJwt] = useState(true); const [pending, setPending] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setPending(true); const response = await fetch(`/api/projects/${projectId}/supabase/functions`); const body = await response.json() as { data?: FunctionItem[]; error?: { message?: string } }; setPending(false); if (!response.ok) setError(body.error?.message ?? "Functions could not be loaded."); else { setItems(body.data ?? []); setError(null); } }
  useEffect(() => { fetch(`/api/projects/${projectId}/supabase/functions`).then(async (response) => ({ response, body: await response.json() as { data?: FunctionItem[]; error?: { message?: string } } })).then(({ response, body }) => { setPending(false); if (!response.ok) setError(body.error?.message ?? "Functions could not be loaded."); else setItems(body.data ?? []); }).catch(() => { setPending(false); setError("Functions could not be loaded."); }); }, [projectId]);
  async function deploy() { setPending(true); setError(null); const response = await fetch(`/api/projects/${projectId}/supabase/functions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, source, verifyJwt }) }); const body = await response.json() as { error?: { message?: string } }; setPending(false); if (!response.ok) { setError(body.error?.message ?? "Deployment failed."); return; } await load(); }
  async function remove(item: FunctionItem) { const name = item.slug ?? ""; const confirmation = window.prompt(`Type ${name} to delete this function.`); if (confirmation !== name) return; setPending(true); const response = await fetch(`/api/projects/${projectId}/supabase/functions?slug=${encodeURIComponent(name)}&confirm=${encodeURIComponent(confirmation)}`, { method: "DELETE" }); setPending(false); if (!response.ok) { const body = await response.json() as { error?: { message?: string } }; setError(body.error?.message ?? "Deletion failed."); return; } setSelected(null); await load(); }
  return <div className="function-workspace"><aside><header><span>Functions</span><button onClick={() => { setSelected(null); setSlug("new-function"); setSource(initialSource); }}><Plus /></button></header>{items.map((item) => <button className={selected === item.slug ? "active" : ""} key={item.id ?? item.slug} onClick={() => { setSelected(item.slug ?? null); setSlug(item.slug ?? "function"); }}><FileCode2 /><span><b>{item.slug}</b><small>{item.status ?? "deployed"} · v{item.version ?? "?"}</small></span></button>)}{!items.length && !pending && <p>No functions deployed.</p>}</aside><section><div className="editor-toolbar"><strong>{slug}<span> · {resourceName}</span></strong><label className="jwt-check"><input type="checkbox" checked={verifyJwt} onChange={(event) => setVerifyJwt(event.target.checked)} /> Verify JWT</label>{selected && <button className="product-button danger" onClick={() => void remove(items.find((item) => item.slug === selected) ?? { slug: selected })}><Trash2 /> Delete</button>}<button className="product-button" onClick={() => void load()}><RefreshCw /></button><button className="product-button primary" disabled={pending || !slug} onClick={() => void deploy()}><CloudUpload /> {pending ? "Working…" : "Deploy"}</button></div><div className="function-slug"><label>Function slug<input value={slug} onChange={(event) => setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""))} /></label><span>Runtime provider: Supabase Edge Functions</span></div>{error && <div className="inline-error"><AlertTriangle />{error}<button onClick={() => setError(null)}><X /></button></div>}<div className="function-editor"><MonacoEditor language="typescript" theme="vs-dark" value={source} onChange={(value) => setSource(value ?? "")} options={{ minimap: { enabled: false }, fontFamily: "var(--mono)", fontSize: 13, lineHeight: 22, automaticLayout: true, scrollBeyondLastLine: false }} /></div></section></div>;
}
