import { Activity, AlertTriangle, Braces, CheckCircle2, Database, ExternalLink, FileCode2, LockKeyhole, Plus, Shield, Table2, TerminalSquare } from "lucide-react";
import type { ProjectData } from "@/lib/project-data";
import { AuthManager } from "./auth-manager";
import { CopyButton } from "./copy-button";
import { FunctionsManager } from "./functions-manager";
import { KeyManager } from "./key-manager";
import { ProviderConnect } from "./provider-connect";
import { ResourceManager } from "./resource-manager";
import { SettingsManager } from "./settings-manager";
import { SqlEditor } from "./sql-editor";
import { TableEditor } from "./table-editor";

interface ProductPageProps { section: string; project: { id: string; name: string; workspaceId: string; description: string | null }; data: ProjectData }
const providerName = (provider: string) => provider === "cloudflare-d1" ? "Cloudflare D1" : provider[0]!.toUpperCase() + provider.slice(1);
const bytes = (value: number | null) => value === null ? "Unknown" : value < 1_000_000 ? `${Math.round(value / 1_000)} KB` : value < 1_000_000_000 ? `${Math.round(value / 1_000_000)} MB` : `${(value / 1_000_000_000).toFixed(1)} GB`;
const providers = ["supabase", "neon", "cloudflare-d1"] as const;

function EmptyCapability({ icon: Icon, title, text, children }: { icon: typeof Database; title: string; text: string; children?: React.ReactNode }) {
  return <div className="empty-panel"><div><span className="empty-icon"><Icon /></span><h2>{title}</h2><p>{text}</p>{children && <div className="empty-actions">{children}</div>}</div></div>;
}

function Overview({ project, data }: Omit<ProductPageProps, "section">) {
  const connected = data.connections.filter((item) => ["connected", "healthy", "provisioning"].includes(item.state)).length;
  const healthy = data.resources.filter((item) => item.state === "healthy" || item.state === "connected").length;
  const used = data.resources.reduce((sum, resource) => sum + (resource.storageUsedBytes ?? 0), 0);
  const limit = data.resources.reduce((sum, resource) => sum + (resource.storageLimitBytes ?? 0), 0);
  return <div className="product-page"><div className="page-header"><div><h1>{project.name}</h1><p>{project.description ?? "One logical backend across customer-owned databases."}</p></div><div className="page-actions"><a className="product-button" href={`/app/${project.id}/database/sql`}><TerminalSquare /> Open SQL</a><a className="product-button primary" href={`/app/${project.id}/infrastructure/nodes`}><Plus /> Add capacity</a></div></div>{!data.resources.length && <div className="status-banner"><AlertTriangle /> No physical database is attached. Connect a provider below; the MeldDB project remains valid.</div>}<div className="overview-grid">
    <section className="panel health-panel"><div className="panel-header"><h2>Backend health</h2><span>LIVE CONTROL PLANE</span></div><div className="health-summary"><span className="health-orb">{healthy === data.resources.length && data.resources.length ? <CheckCircle2 /> : <Activity />}</span><div><h3>{!data.resources.length ? "Waiting for a database node" : healthy === data.resources.length ? "All attached nodes healthy" : "A node needs attention"}</h3><p>{connected} provider connections · {data.resources.length} physical nodes · {data.tables.length} logical tables</p></div></div><div className="provider-list">{providers.map((provider, index) => { const connection = data.connections.find((item) => item.provider === provider); const resource = data.resources.find((item) => item.provider === provider); return <div className="provider-list-row" key={provider}><i>{index + 1}</i><div><strong>{providerName(provider)}</strong><small>{resource ? `${resource.name} · ${resource.dialect}` : connection ? "Connected · database not attached" : "Not connected"}</small></div><span className={`state-badge ${resource?.state === "healthy" || connection?.state === "healthy" ? "healthy" : connection?.state === "quota_full" ? "warning" : ""}`}><i />{resource?.state ?? connection?.state?.replaceAll("_", " ") ?? "offline"}</span></div>; })}</div></section>
    <section className="panel"><div className="panel-header"><h2>Logical storage</h2><span>PROVIDER BREAKDOWN</span></div><div className="capacity-mini"><div className="capacity-number">{bytes(used)} <span>/ {limit ? bytes(limit) : "unknown"}</span></div><div className="capacity-bar"><i style={{ width: limit ? `${Math.min(100, used / limit * 100)}%` : "0%" }} /></div><p>Known database storage only. Compute, request, and egress limits remain provider-specific and are not pooled.</p></div></section>
    <section className="panel activity-panel"><div className="panel-header"><h2>Recent activity</h2><span>{data.logs.length} retained query events</span></div><table className="data-table"><thead><tr><th>Operation</th><th>Target</th><th>Status</th><th>Latency</th><th>Time</th><th>Request</th></tr></thead><tbody>{data.logs.slice(0, 8).map((log) => <tr key={log.id}><td>{log.operation.toUpperCase()}</td><td>{log.target}</td><td><span className={`state-badge ${log.status === "success" ? "healthy" : "warning"}`}><i />{log.status}</span></td><td>{log.durationMs === null ? "—" : `${log.durationMs} ms`}</td><td>{new Date(log.createdAt).toLocaleString()}</td><td><code>{log.requestId.slice(0, 8)}</code></td></tr>)}{!data.logs.length && <tr className="table-empty-row"><td colSpan={6}>No query activity yet. MeldDB stores bounded metadata, never result sets.</td></tr>}</tbody></table></section>
  </div></div>;
}

function SchemaPage({ data }: { data: ProjectData }) {
  return <div className="product-page"><div className="page-header"><div><h1>Logical Schema</h1><p>The canonical contract your applications use, independent of physical placement.</p></div></div>{data.tables.length ? <div className="schema-cards">{data.tables.map((table) => <section className="panel" key={table.id}><div className="panel-header"><h2>{table.schema}.{table.name}</h2><span>{table.columns.length} columns</span></div><table className="data-table"><thead><tr><th>Column</th><th>Canonical type</th><th>Nullable</th><th>Key</th></tr></thead><tbody>{table.columns.map((column) => <tr key={column.name}><td><code>{column.name}</code></td><td>{column.type}</td><td>{column.nullable ? "Yes" : "No"}</td><td>{column.primaryKey ? "Primary" : "—"}</td></tr>)}</tbody></table></section>)}</div> : <EmptyCapability icon={Table2} title="No logical schema yet" text="Create a table after attaching a database. MeldDB records its canonical columns and physical shard placement." />}</div>;
}

function AuthPage({ project, data }: Omit<ProductPageProps, "section">) {
  const supabase = data.resources.find((item) => item.provider === "supabase");
  return <div className="product-page"><div className="page-header"><div><h1>Auth</h1><p>Customer authentication configuration, distinct from your MeldDB account.</p></div></div>{supabase ? <section className="panel"><div className="panel-header"><h2>Supabase Auth</h2><span>MANAGED CAPABILITY</span></div><AuthManager projectId={project.id} resourceName={supabase.name} /></section> : <EmptyCapability icon={Shield} title="Authentication needs a managed Auth provider" text="Supabase supports customer Auth management in MeldDB. Connect Supabase and attach a project to configure it here."><a className="product-button primary" href={`/app/${project.id}/infrastructure/nodes`}>Connect Supabase</a></EmptyCapability>}</div>;
}

function FunctionsPage({ project, data }: Omit<ProductPageProps, "section">) {
  const supabase = data.resources.find((item) => item.provider === "supabase");
  return <div className="product-page"><div className="page-header"><div><h1>Functions</h1><p>Deploy and inspect server-side functions on an explicit runtime provider.</p></div></div>{supabase ? <FunctionsManager projectId={project.id} resourceName={supabase.name} /> : <EmptyCapability icon={FileCode2} title="Functions need a runtime provider" text="Attach a Supabase project to deploy Edge Functions. MeldDB will remain transparent about where each function runs."><a className="product-button primary" href={`/app/${project.id}/infrastructure/nodes`}>Connect Supabase</a></EmptyCapability>}</div>;
}

function ContextPage({ project, data }: Omit<ProductPageProps, "section">) {
  const context = `Project: ${project.name}\n\nLogical schema:\n${data.tables.length ? data.tables.map((table) => `- ${table.schema}.${table.name}(${table.columns.map((column) => `${column.name} ${column.type}${column.primaryKey ? " PK" : ""}${column.nullable ? "" : " NOT NULL"}`).join(", ")})`).join("\n") : "- No tables cataloged"}\n\nPhysical nodes:\n${data.resources.length ? data.resources.map((resource) => `- ${providerName(resource.provider)}: ${resource.name} (${resource.dialect}, ${resource.state})`).join("\n") : "- No nodes attached"}\n\nAuth: ${data.resources.some((item) => item.provider === "supabase") ? "Supabase Auth available" : "No managed Auth provider"}\nFunctions: ${data.functionCount} cataloged\n\nUnified SQL limitations:\n- One logical table per statement\n- No cross-provider JOIN or transaction\n- Writes to sharded tables require a routing key\n- Results are capped at 1,000 rows`;
  return <div className="product-page"><div className="page-header"><div><h1>Developer Context</h1><p>A credential-free backend map for developers and coding agents.</p></div><CopyButton text={context} /></div><div className="split-grid context-layout"><div className="code-panel"><header><span>melddb-context.txt</span><span>NO SECRETS</span></header><pre>{context}</pre></div><section className="panel"><div className="panel-header"><h2>REST gateway</h2><span>SERVER ONLY</span></div><div className="code-panel inset"><header><span>POST /api/v1/projects/{project.id}/query</span></header><pre>{`Authorization: Bearer mdb_live_…\nContent-Type: application/json\n\n{\n  "sql": "SELECT * FROM users LIMIT $1",\n  "params": [20]\n}`}</pre></div><div className="context-warning"><LockKeyhole /> Keep MeldDB API keys in server-side environment variables. Never use a <code>NEXT_PUBLIC_</code> variable.</div></section></div></div>;
}

function LogsPage({ data }: { data: ProjectData }) {
  const all = [...data.logs.map((item) => ({ ...item, kind: "Query", action: item.operation, outcome: item.status })), ...data.audits.map((item) => ({ ...item, kind: "Audit", target: "control-plane", durationMs: null, errorMessage: null, action: item.action, status: item.outcome }))].sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt));
  return <div className="product-page"><div className="page-header"><div><h1>Logs</h1><p>Bounded operational metadata. Credentials, authorization headers, and result payloads are excluded.</p></div></div><section className="panel"><div className="panel-header"><h2>Recent events</h2><span>RETENTION {process.env.QUERY_LOG_RETENTION_DAYS ?? "7"} DAYS</span></div><table className="data-table"><thead><tr><th>Type</th><th>Operation</th><th>Target</th><th>Status</th><th>Latency</th><th>Time</th><th>Request ID</th></tr></thead><tbody>{all.map((item) => <tr key={`${item.kind}-${item.id}`}><td>{item.kind}</td><td>{item.action}</td><td>{item.target}</td><td><span className={`state-badge ${item.status === "success" ? "healthy" : "warning"}`}><i />{item.status}</span></td><td>{item.durationMs === null ? "—" : `${item.durationMs} ms`}</td><td>{new Date(item.createdAt).toLocaleString()}</td><td><code>{item.requestId}</code></td></tr>)}{!all.length && <tr className="table-empty-row"><td colSpan={7}>No events have been retained for this project.</td></tr>}</tbody></table></section></div>;
}

function NodesPage({ project, data }: Omit<ProductPageProps, "section">) {
  return <div className="product-page"><div className="page-header"><div><h1>Infrastructure</h1><p>Real customer-owned database resources. Disconnecting MeldDB does not delete them.</p></div></div><section className="panel provider-connections"><div className="panel-header"><h2>Provider connections</h2><span>WORKSPACE SCOPED</span></div>{providers.map((provider) => { const connection = data.connections.find((item) => item.provider === provider); const attached = data.resources.some((item) => item.provider === provider); return <div className="connection-row" key={provider}><span className="provider-symbol">{provider === "cloudflare-d1" ? "D1" : provider.slice(0, 2).toUpperCase()}</span><div><strong>{providerName(provider)}</strong><small>{connection ? connection.accountName ?? "Authorized account" : provider === "neon" ? "API key connection" : "OAuth connection"}</small></div><ProviderConnect provider={provider} projectId={project.id} workspaceId={project.workspaceId} connected={Boolean(connection)} configured={provider === "supabase" ? Boolean(process.env.SUPABASE_OAUTH_CLIENT_ID && process.env.SUPABASE_OAUTH_CLIENT_SECRET) : provider === "cloudflare-d1" ? Boolean(process.env.CLOUDFLARE_OAUTH_CLIENT_ID && process.env.CLOUDFLARE_OAUTH_CLIENT_SECRET) : true} />{connection && <ResourceManager projectId={project.id} provider={provider} hasAttached={attached} />}</div>; })}</section><section className="panel nodes-panel"><div className="panel-header"><h2>Physical nodes</h2><span>{data.resources.length} ATTACHED</span></div><div className="table-scroll"><table className="data-table node-table"><thead><tr><th>Provider</th><th>Resource</th><th>Region</th><th>Database</th><th>Storage used</th><th>Limit</th><th>Latency</th><th>Last check</th><th>State</th></tr></thead><tbody>{data.resources.map((resource) => <tr key={resource.id}><td><span className="provider-symbol">{resource.provider === "cloudflare-d1" ? "D1" : resource.provider.slice(0, 2).toUpperCase()}</span>{providerName(resource.provider)}</td><td>{resource.consoleUrl ? <a href={resource.consoleUrl} target="_blank" rel="noreferrer">{resource.name} <ExternalLink /></a> : resource.name}</td><td>{resource.region ?? (resource.provider === "cloudflare-d1" ? "Global" : "Unknown")}</td><td>{resource.dialect === "postgresql" ? "Postgres" : "SQLite"}</td><td>{bytes(resource.storageUsedBytes)}</td><td>{bytes(resource.storageLimitBytes)}</td><td>{resource.latencyMs === null ? "—" : `${resource.latencyMs} ms`}</td><td>{resource.lastCheckedAt ? new Date(resource.lastCheckedAt).toLocaleString() : "Not checked"}</td><td><span className={`state-badge ${resource.state === "healthy" ? "healthy" : ""}`}><i />{resource.state}</span></td></tr>)}{!data.resources.length && <tr className="table-empty-row"><td colSpan={9}>No databases attached. Connect a provider above, then select or create a resource.</td></tr>}</tbody></table></div></section></div>;
}

function CapacityPage({ data }: { data: ProjectData }) {
  return <div className="product-page"><div className="page-header"><div><h1>Capacity</h1><p>Provider quotas shown independently. Limits may change; API values take precedence over dated fallbacks.</p></div></div><div className="capacity-grid">{providers.map((provider) => { const capacity = data.capacities.find((item) => item.provider === provider); const resourceCount = data.resources.filter((item) => item.provider === provider).length; const limit = capacity?.resourceLimit; const used = capacity?.resourcesUsed ?? resourceCount; return <section className="panel" key={provider}><div className="panel-header"><h2>{providerName(provider)}</h2><span>{capacity?.source?.replaceAll("_", " ") ?? "NOT CHECKED"}</span></div><div className="capacity-card-body"><strong>{used} <span>/ {limit ?? "?"}</span></strong><p>{capacity?.resourcesRemaining === null || capacity?.resourcesRemaining === undefined ? "Connect to read current capacity" : `${capacity.resourcesRemaining} resource slots remaining`}</p><div className="capacity-bar"><i style={{ width: limit ? `${Math.min(100, used / limit * 100)}%` : "0%" }} /></div><dl><div><dt>Per resource storage</dt><dd>{bytes(capacity?.storagePerResourceBytes ?? null)}</dd></div><div><dt>Plan</dt><dd>{capacity?.plan ?? "Unknown"}</dd></div><div><dt>Checked</dt><dd>{capacity ? new Date(capacity.checkedAt).toLocaleString() : "Never"}</dd></div></dl></div></section>; })}</div><div className="status-banner capacity-note"><AlertTriangle /> Capacity is not fungible: PostgreSQL and SQLite nodes retain their own compute, request, egress, feature, and storage constraints.</div></div>;
}

function SettingsPage({ project }: Pick<ProductPageProps, "project">) {
  return <div className="product-page"><div className="page-header"><div><h1>Project Settings</h1><p>Identity, behavior, and destructive project operations.</p></div></div><SettingsManager project={project} /></div>;
}

export function ProductPage(props: ProductPageProps) {
  const { section, project, data } = props;
  if (section === "overview") return <Overview project={project} data={data} />;
  if (section === "database/tables") return <div className="product-page"><TableEditor projectId={project.id} tables={data.tables} resources={data.resources.map(({ id, name, provider, dialect }) => ({ id, name, provider, dialect }))} /></div>;
  if (section === "database/sql") return <div className="product-page"><SqlEditor projectId={project.id} resources={data.resources.map(({ id, name, provider, dialect }) => ({ id, name, provider, dialect }))} tableNames={data.tables.map((table) => table.name)} /></div>;
  if (section === "database/schema") return <SchemaPage data={data} />;
  if (section === "auth") return <AuthPage project={project} data={data} />;
  if (section === "functions") return <FunctionsPage project={project} data={data} />;
  if (section === "developers/api-keys") return <div className="product-page"><KeyManager projectId={project.id} initialKeys={data.apiKeys} /></div>;
  if (section === "developers/context") return <ContextPage project={project} data={data} />;
  if (section === "developers/logs") return <LogsPage data={data} />;
  if (section === "infrastructure/nodes") return <NodesPage project={project} data={data} />;
  if (section === "infrastructure/capacity") return <CapacityPage data={data} />;
  if (section === "settings") return <SettingsPage project={project} />;
  return <div className="product-page"><EmptyCapability icon={Braces} title="Page not found" text="This project surface does not exist." /></div>;
}
