"use client";

import { AlertTriangle, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { CopyButton } from "./copy-button";

export function SettingsManager({ project }: { project: { id: string; name: string } }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [confirmation, setConfirmation] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function remove() { setPending(true); setError(null); const response = await fetch(`/api/projects/${project.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation, preserveProviderResources: true }) }); const body = await response.json() as { error?: { message?: string } }; setPending(false); if (!response.ok) { setError(body.error?.message ?? "Project deletion failed."); return; } router.push("/app"); router.refresh(); }
  return <><div className="settings-list"><div className="setting-row"><div><h3>Project ID</h3><p><code>{project.id}</code></p></div><CopyButton value={project.id} /></div><div className="setting-row"><div><h3>Unified query result limit</h3><p>Results are capped at 1,000 rows and remain ephemeral.</p></div><b>1,000</b></div><div className="setting-row"><div><h3>Default delete behavior</h3><p>Deleting this MeldDB project removes control-plane metadata only.</p></div><b>Preserve cloud resources</b></div></div><section className="danger-zone"><div className="panel-header"><h2>Danger zone</h2></div><div className="danger-row"><div><h3>Delete MeldDB project</h3><p>Underlying Supabase, Neon, and D1 resources are preserved. Logical schema, keys, placements, and project metadata are deleted.</p></div><button className="product-button danger" onClick={() => setOpen(true)}><Trash2 /> Delete project</button></div></section>{open && <div className="command-overlay" onMouseDown={() => setOpen(false)}><div className="provider-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><AlertTriangle /><span><b>Delete {project.name}</b><small>This only removes MeldDB control-plane state.</small></span></div><button onClick={() => setOpen(false)}><X /></button></header><div className="modal-form"><div className="status-banner"><AlertTriangle /> Provider databases will not be deleted.</div><label>Type <b>{project.name}</b> to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoFocus /></label></div>{error && <div className="form-error">{error}</div>}<footer><button className="product-button" onClick={() => setOpen(false)}>Cancel</button><button className="product-button danger" disabled={pending || confirmation !== project.name} onClick={() => void remove()}>{pending ? "Deleting…" : "Delete MeldDB project"}</button></footer></div></div>}</>;
}
